language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: Ll1okqipf8rjZJi4BEyO6fw2EtGUape5EMAQtyM8bsbKuq9+zJX4VWyfsrLrr3TacEn7YH2PwHfa5zAq4H3nkVmG1dj49iPinuGniR6pKq7aWQkVJlukA03U46flMxXZRhsu6b2wp9t1kGz2BW/fdCblCF086TBRuaJIcrH11RrANOWpHbrv90i80E2lZ+T7pXTiaFfRNFc94VJF+VcZ+dXZRSeZXWBOv8TY8xSt4ILd79yC9ZsEe5DiVfrKlGwtNKtoDsoAV4gv7GxwRXTV++ToWJIbDyJ19MLPK0V6b5ceZTlPnIFKaavpJbfIrQN7pa4p7vG6TYqdqtC3z1t13YchXF/hMkqssudi6CExiHF/SwgQ7NYeeHqdNh8qFUVLsg8gUtTpzZtj2R+sW5Wuhrp5wUHCyIIWwrYpernNMxpy1kq29hYY4Rt0I5oNDms1GPsrXjXePh3LancnUQ7T4yPrEc9oN9t3K7IafBTOG7X9XJMIIS9zO0LDjmjyzARLZxA7qckfFdDAkE5DZAON/UbGaiZFBZIjuMoAi6FQ+egfpT4fkDLaI6undv4v7MmgsdQEKXuFnLHiY/n0s6rvSMISazZoMcvd4AV1tR5qwRpEATCai3xa1JzcCwpt6J1HtKSt60qu2q9ViiSGXk9CdddxFq6mHo1ek/mT5r2enlI=
  app: afternoon-escarpment-52240
  on:
    repo: rrcheatham/retirement-calc-api
